import type { Project } from "./types";

// Project names and one-line descriptors are real.
// PLACEHOLDER: everything else (stories, numbers, decisions) is a stand-in to be replaced.

export const projects: Project[] = [
  {
    slug: "curator",
    title: "Curator",
    short: "Reading & saved stories",
    note: "read with more care",
    tagline: "A reading app with source context and a library of saved stories.",
    outcome: "From side project to launch build",
    year: "2026",
    duration: "Ongoing",
    role: "Founder & engineer",
    team: "Solo, with design advisors",
    type: ["Product", "Web", "Mobile"],
    stack: ["Next.js", "React Native", "TypeScript", "PostgreSQL", "Redis", "Cloudflare"],
    featured: true,
    status: "Preparing for launch",
    links: { live: "#" },
    layers: [
      { name: "Reader", detail: "Web + mobile, one design language" },
      { name: "Client", detail: "Shared TypeScript core, optimistic UI" },
      { name: "API", detail: "Typed RPC at the edge" },
      { name: "Workers", detail: "Parsing, source context, digests" },
      { name: "Library", detail: "Postgres + Redis streams" },
    ],
    keyLayer: 3,
    metrics: [
      { value: "3", label: "Platforms, one codebase" },
      { value: "0.8s", label: "Save-to-sync, p95" },
      { value: "1.2k", label: "Beta stories saved" },
    ],
    backstory: [
      "Curator started as a folder of links I never opened again. Read-later apps, notes and group chats were full of things I meant to read, and none of them felt like a library I wanted to return to.",
      "The question that turned it into a product was simple: what if saving a story was the beginning of reading it carefully, with its source and context attached, not the end?",
    ],
    problem: "People save far more than they ever read, and lose the context of where a story came from and why it mattered.",
    constraints: [
      "Built and maintained by one engineer",
      "Must feel instant on mid-range Android phones",
      "Saved stories must sync across web and mobile without conflicts",
    ],
    myRole: ["Product direction, interaction design and the full stack", "Designed the sync model and the parsing pipeline", "Runs the beta and its feedback loop"],
    process: [
      { stage: "Design", text: "Paper prototypes of the 'come back and read' moment before a single screen in Figma." },
      { stage: "Build", text: "A shared TypeScript core so web and mobile behave identically, with optimistic writes everywhere." },
      { stage: "Ship", text: "Weekly beta builds, a public changelog, and one metric that matters: stories actually read." },
    ],
    decisions: [
      {
        title: "Context is computed, not typed",
        options: ["Ask users to tag sources", "Extract source context automatically"],
        choice: "Extract source context automatically",
        why: "Every extra field at save time cut saves in half during testing.",
      },
      {
        title: "One codebase, two surfaces",
        options: ["Native per platform", "Flutter", "React Native + shared TS core"],
        choice: "React Native + shared TS core",
        why: "As a solo engineer, a single mental model was worth more than the last 5% of native polish.",
      },
    ],
    hardPart: {
      title: "Saving that never waits",
      body: [
        "Fetching a story's source meant loading arbitrary pages, which can be slow, broken or hostile. The first version did it inline, and saving sometimes took four seconds.",
        "The fix was to make the save instant and the context a promise: a worker fills it in later, and the interface reserves the exact space so nothing jumps when it arrives.",
      ],
    },
    reflection: "I would have opened the beta earlier with fewer features. The best ideas in Curator came from readers, not from my roadmap.",
  },
  {
    slug: "talentorbit",
    title: "TalentOrbit",
    short: "Hiring platform",
    note: "hire on evidence",
    tagline: "A hiring platform that matches people and roles on evidence, not keywords.",
    outcome: "Shortlists in hours instead of weeks",
    year: "2025",
    duration: "8 months",
    role: "Full-stack engineer",
    team: "Small product team",
    type: ["Product", "Web", "Systems"],
    stack: ["React", "Node.js", "TypeScript", "PostgreSQL", "Elasticsearch", "AWS"],
    featured: true,
    links: {},
    layers: [
      { name: "Workspace", detail: "Recruiter and candidate views" },
      { name: "Client", detail: "Realtime pipeline boards" },
      { name: "API", detail: "Roles, applications, feedback" },
      { name: "Matching", detail: "Signals, scoring, explanations" },
      { name: "Data", detail: "Postgres + search index" },
    ],
    keyLayer: 3,
    metrics: [
      { value: "70%", label: "Less time to shortlist" },
      { value: "2", label: "Sides of the marketplace" },
      { value: "4.6★", label: "Recruiter rating" },
    ],
    backstory: [
      "Every hiring manager I spoke to had the same complaint: too many applications, too little signal. Keyword filters threw out good people and let through good writers of CVs.",
    ],
    problem: "Screening was slow and noisy, and candidates never learned why they were rejected.",
    constraints: ["Explainable matching, with no black boxes", "Fair to candidates from non-traditional paths", "Fast enough for live pipeline boards"],
    myRole: ["Built the pipeline board and its realtime updates", "Designed the matching explanations", "Owned search and indexing"],
    process: [
      { stage: "Design", text: "Sat in on real screening calls to see which signals recruiters actually trusted." },
      { stage: "Build", text: "Scored matches with human-readable reasons attached to every score." },
      { stage: "Ship", text: "Rolled out to a handful of teams first, with weekly calibration sessions." },
    ],
    decisions: [
      {
        title: "Explain every score",
        options: ["Opaque ranking model", "Rule-based scores with reasons"],
        choice: "Rule-based scores with reasons",
        why: "Recruiters only trusted rankings they could argue with.",
      },
    ],
    hardPart: {
      title: "Search that stays in sync",
      body: ["Keeping the search index consistent with live pipeline edits needed an outbox pattern and idempotent indexers."],
    },
    reflection: "Fairness is a product requirement, not a model property. Designing the explanation first made everything downstream better.",
  },
  {
    slug: "kalakari",
    title: "Kalakari",
    short: "Artisan marketplace",
    note: "buy from the maker",
    tagline: "A marketplace that connects Indian artisans directly with the people who buy their work.",
    outcome: "Makers sell direct, without middlemen",
    year: "2024",
    duration: "6 months",
    role: "Lead engineer",
    team: "3 engineers, 1 designer",
    type: ["Product", "Mobile", "Web"],
    stack: ["Next.js", "React Native", "TypeScript", "PostgreSQL", "Razorpay", "Cloudinary"],
    featured: true,
    links: {},
    layers: [
      { name: "Storefront", detail: "Stories behind every piece" },
      { name: "Maker app", detail: "List a product in two minutes" },
      { name: "Commerce API", detail: "Orders, payouts, shipping" },
      { name: "Media", detail: "Photos that load on 3G" },
      { name: "Ledger", detail: "Payments and payouts" },
    ],
    keyLayer: 1,
    metrics: [
      { value: "2 min", label: "To list a product" },
      { value: "120+", label: "Makers onboarded" },
      { value: "0%", label: "Middleman margin" },
    ],
    backstory: ["Kalakari means artistry. It began with a visit to a weaving village where the makers earned a fraction of what their work sold for in cities."],
    problem: "Artisans depended on middlemen to reach buyers, and most selling apps assumed fluent English and fast internet.",
    constraints: ["Low-end phones and patchy networks", "Vernacular-first interface", "Payouts that makers can trust"],
    myRole: ["Built the maker app and the listing flow", "Designed the payout ledger", "Led a small engineering team"],
    process: [
      { stage: "Design", text: "Voice-first listing prototypes tested with makers, in their language." },
      { stage: "Build", text: "Offline-capable listing with background photo uploads." },
      { stage: "Ship", text: "Village-by-village onboarding with in-person training." },
    ],
    decisions: [
      {
        title: "Voice before forms",
        options: ["Classic product form", "Voice notes transcribed into listings"],
        choice: "Voice notes transcribed into listings",
        why: "Makers could describe their work far better than they could type it.",
      },
    ],
    hardPart: { title: "Photos on 3G", body: ["Uploads resumed across network drops and compressed on device before leaving the phone."] },
    reflection: "The best feature was a phone number that a real person answered.",
  },
  {
    slug: "flood-archive",
    title: "Flood Archive",
    short: "Vadodara flood history",
    note: "remember the water",
    tagline: "A public archive of Vadodara's floods: maps, records and the stories of the people who lived through them.",
    outcome: "A city's memory, mapped and searchable",
    year: "2024",
    duration: "Personal project",
    role: "Designer & engineer",
    team: "Solo, with local contributors",
    type: ["Web", "Open source"],
    stack: ["Next.js", "MapLibre", "TypeScript", "PostGIS", "Python"],
    featured: true,
    links: { live: "#" },
    layers: [
      { name: "Stories", detail: "First-hand accounts, by street" },
      { name: "Map", detail: "Water levels across the years" },
      { name: "Timeline", detail: "Every recorded flood" },
      { name: "Records", detail: "Digitised reports and data" },
      { name: "Archive", detail: "PostGIS + open datasets" },
    ],
    keyLayer: 1,
    metrics: [
      { value: "50+", label: "Years of records" },
      { value: "300+", label: "Stories collected" },
      { value: "100%", label: "Open data" },
    ],
    backstory: [
      "Vadodara floods, and every time it does the city is surprised. The records existed, scattered across reports, newspapers and people's memories, but nobody could see them together.",
    ],
    problem: "Flood history was fragmented and hard to access, so each flood felt unprecedented.",
    constraints: ["Data from very different sources and eras", "Must work on any phone during an emergency", "Respectful handling of personal stories"],
    myRole: ["Research, design and engineering", "Digitised and cleaned historical records", "Built the contribution flow for stories"],
    process: [
      { stage: "Design", text: "Started from one street and one family's story, then zoomed out." },
      { stage: "Build", text: "A map-first interface over PostGIS, with a static fallback for slow networks." },
      { stage: "Ship", text: "Released openly, with datasets anyone can download." },
    ],
    decisions: [
      {
        title: "Stories next to data",
        options: ["Data dashboard only", "Personal stories pinned to the map"],
        choice: "Personal stories pinned to the map",
        why: "Numbers explain a flood; stories make people prepare for the next one.",
      },
    ],
    hardPart: { title: "Making old records line up", body: ["Decades of reports used different units, place names and gauge locations. Reconciling them took longer than building the site."] },
    reflection: "This is the project I'm proudest of, because it's for my city.",
  },
  {
    slug: "portfolio",
    title: "Portfolio",
    short: "Three versions, one practice",
    note: "practice in public",
    tagline: "This site, and the two before it: a running record of how I design and build.",
    outcome: "Three versions, one practice",
    year: "2026",
    duration: "2019 to now",
    role: "Designer & engineer",
    team: "Solo",
    type: ["Web", "Open source"],
    stack: ["Next.js", "GSAP", "Lenis", "TypeScript"],
    featured: false,
    href: "/archive",
    links: {},
    layers: [],
    keyLayer: 0,
    metrics: [],
    backstory: [],
    problem: "",
    constraints: [],
    myRole: [],
    process: [],
    decisions: [],
    hardPart: { title: "", body: [] },
    reflection: "",
  },
];

export const featuredProjects = projects.filter((p) => p.featured);
export const getProject = (slug: string) => projects.find((p) => p.slug === slug);
export const projectHref = (p: Project) => p.href ?? `/work/${p.slug}`;
